backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: pages
    label: Page
    folder: pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title, required: false }
      - { name: subtitle, label: Subtitle, required: false }
      - { name: teaser, label: Teaser, required: false }
      - { name: body, label: Body, widget: markdown, required: false }
